src/RealmHelper.Web/Controllers/RealmController.cs
using RealmHelper.Application.Models.Minecraft;
using RealmHelper.Application.Models.Minecraft.Requests;
using RealmHelper.Application.Services;
using RealmHelper.Domain.Models.Minecraft;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;

namespace RealmHelper.Web.Controllers;

[Authorize]
[ApiController]
[AuthorizeForScopes]
public abstract class RealmController<TSlotOptions> : ControllerBase where TSlotOptions : SlotOptionsDto
{
    [HttpGet("Slot/{slotId:int}/Backup/{backupId?}")]
    public abstract Task<IActionResult> DownloadBackup(long realmId, int slotId, string? backupId = default);

    [HttpPost("Slot/{slotId:int}/Backup/{backupId?}")]
    public abstract Task<IActionResult> UploadBackup(long realmId, int slotId, string? backupId = default);

    [HttpPatch("Slot/{slotId:int}")]
    public abstract Task<IActionResult> UpdateSlot(long realmId, int slotId,
        [FromBody] SlotUpdateRequest<TSlotOptions> request);

    [HttpPut("Description")]
    public abstract Task<IActionResult> UpdateDescription(long realmId, [FromBody] DescriptionUpdateRequest request);

    [HttpPut("Slot/{slotId:int}")]
    public abstract Task<IActionResult> ActivateSlot(long realmId, int slotId);

    [HttpPost("Open")]
    public abstract Task<IActionResult> Open(long realmId);
    
    [HttpPost("Close")]
    public abstract Task<IActionResult> Close(long realmId);
    
    [HttpPost("Reset")]
    public abstract Task<IActionResult> Reset(long realmId);

    [HttpPost("Invites/{player}")]
    public abstract Task<IActionResult> Invite(long realmId, string player);

    [HttpDelete("Invites/{player}")]
    public abstract Task<IActionResult> Uninvite(long realmId, string player);
}

[Route("Api/Java/Realm/{realmId:long}")]
public class JavaRealmController : RealmController<SlotOptionsDto>
{
    private readonly IJavaRealmService _realmService;

    public JavaRealmController(IJavaRealmService realmService) =>
        _realmService = realmService;
    
    public override async Task<IActionResult> DownloadBackup(long realmId, int slotId, string? backupId = default)
    {
        var data = await _realmService.DownloadBackupAsync(realmId, slotId, backupId);

        return File(data.Content, data.ContentType, data.FileName);
    }

    public override async Task<IActionResult> UploadBackup(long realmId, int slotId, string? backupId = default)
    {
        if (backupId is not null)
        {
            await _realmService.RestoreBackupAsync(realmId, backupId);

            return NoContent();
        }
        
        if (!Request.HasFormContentType || Request.Form.Count > 1)
            return BadRequest();

        var file = Request.Form.Files[0];
        var archiveData = new BackupFile
        {
            Name = file.Name,
            FileName = file.FileName,
            Content = file.OpenReadStream(),
            ContentType = file.ContentType
        };

        await _realmService.UploadBackupAsync(realmId, slotId, archiveData);

        return NoContent();
    }

    public override async Task<IActionResult> UpdateSlot(long realmId, int slotId,
        SlotUpdateRequest<SlotOptionsDto> request)
    {
        await _realmService.UpdateBulkAsync(realmId, slotId, request.Description.Name, request.Description.Description,
            request.Options);

        return NoContent();
    }

    [HttpPut("Slot/{slotId:int}/Options")]
    public async Task<IActionResult> UpdateSlotOptions(long realmId, int slotId, [FromBody] SlotOptionsDto request)
    {
        await _realmService.UpdateSlotOptionsAsync(realmId, slotId, request);

        return NoContent();
    }

    public override async Task<IActionResult> UpdateDescription(long realmId, DescriptionUpdateRequest request)
    {
        await _realmService.UpdateDescriptionAsync(realmId, request.Name, request.Description);

        return NoContent();
    }

    public override async Task<IActionResult> ActivateSlot(long realmId, int slotId)
    {
        await _realmService.SwitchSlotAsync(realmId, slotId);

        return NoContent();
    }

    public override async Task<IActionResult> Open(long realmId)
    {
        await _realmService.OpenRealmAsync(realmId);

        return NoContent();
    }

    public override async Task<IActionResult> Close(long realmId)
    {
        await _realmService.CloseRealmAsync(realmId);

        return NoContent();
    }

    public override async Task<IActionResult> Reset(long realmId)
    {
        await _realmService.ResetRealmAsync(realmId);

        return NoContent();
    }

    public override async Task<IActionResult> Invite(long realmId, string player)
    {
        await _realmService.InvitePlayerAsync(realmId, player);

        return NoContent();
    }

    public override async Task<IActionResult> Uninvite(long realmId, string player)
    {
        await _realmService.UninvitePlayerAsync(realmId, player);

        return NoContent();
    }
    
    [HttpPost("Ops/{player}")]
    public async Task<IActionResult> Op(long realmId, string player)
    {
        await _realmService.OpAsync(realmId, player);

        return NoContent();
    }

    [HttpDelete("Ops/{player}")]
    public async Task<IActionResult> Deop(long realmId, string player)
    {
        await _realmService.DeopAsync(realmId, player);

        return NoContent();
    }
}

[Route("Api/Bedrock/Realm/{realmId:long}")]
public class BedrockRealmController : RealmController<BedrockSlotOptionsDto>
{
    private readonly IBedrockRealmService _realmService;

    public BedrockRealmController(IBedrockRealmService realmService) =>
        _realmService = realmService;
    
    public override async Task<IActionResult> DownloadBackup(long realmId, int slotId, string? backupId = default)
    {
        var data = await _realmService.DownloadBackupAsync(realmId, slotId, backupId);

        return File(data.Content, data.ContentType, data.FileName);
    }

    public override async Task<IActionResult> UploadBackup(long realmId, int slotId, string? backupId = default)
    {
        if (backupId is not null)
        {
            await _realmService.RestoreBackupAsync(realmId, backupId);

            return NoContent();
        }
        
        if (!Request.HasFormContentType || Request.Form.Count > 1)
            return BadRequest();

        var file = Request.Form.Files[0];
        var archiveData = new BackupFile
        {
            Name = file.Name,
            FileName = file.FileName,
            Content = file.OpenReadStream(),
            ContentType = file.ContentType
        };

        await _realmService.UploadBackupAsync(realmId, slotId, archiveData);

        return NoContent();
    }

    public override async Task<IActionResult> UpdateSlot(long realmId, int slotId,
        SlotUpdateRequest<BedrockSlotOptionsDto> request)
    {
        await _realmService.UpdateBulkAsync(realmId, slotId, request.Description.Name, request.Description.Description,
            request.Options);

        return NoContent();
    }

    public override async Task<IActionResult> UpdateDescription(long realmId, DescriptionUpdateRequest request)
    {
        await _realmService.UpdateDescriptionAsync(realmId, request.Name, request.Description);

        return NoContent();
    }

    public override async Task<IActionResult> ActivateSlot(long realmId, int slotId)
    {
        await _realmService.SwitchSlotAsync(realmId, slotId);

        return NoContent();
    }

    public override async Task<IActionResult> Open(long realmId)
    {
        await _realmService.OpenRealmAsync(realmId);

        return NoContent();
    }

    public override async Task<IActionResult> Close(long realmId)
    {
        await _realmService.CloseRealmAsync(realmId);

        return NoContent();
    }

    public override async Task<IActionResult> Reset(long realmId)
    {
        await _realmService.ResetRealmAsync(realmId);

        return NoContent();
    }

    public override async Task<IActionResult> Invite(long realmId, string player)
    {
        await _realmService.InvitePlayerAsync(realmId, player);

        return NoContent();
    }

    public override async Task<IActionResult> Uninvite(long realmId, string player)
    {
        await _realmService.UninvitePlayerAsync(realmId, player);

        return NoContent();
    }

    [HttpPost("Blocklist/{player}")]
    public async Task<IActionResult> BlockPlayer(long realmId, string player)
    {
        await _realmService.BlockPlayerAsync(realmId, player);

        return NoContent();
    }
    
    [HttpDelete("Blocklist/{player}")]
    public async Task<IActionResult> UnblockPlayer(long realmId, string player)
    {
        await _realmService.UnblockPlayerAsync(realmId, player);

        return NoContent();
    }

    [HttpPost("Codes/Invite")]
    public async Task<IActionResult> GenerateInviteLink(long realmId)
    {
        await _realmService.GenerateInviteCodeAsync(realmId);

        return NoContent();
    }

    [HttpPut("Permission/Default")]
    public async Task<IActionResult> ChangeDefaultPermission(long realmId, [FromBody] string permission)
    {
        await _realmService.ChangeDefaultPermissionAsync(realmId, permission);

        return NoContent();
    }
    
    [HttpPut("Permission/Player/{player}")]
    public async Task<IActionResult> ChangePlayerPermission(long realmId, string player, [FromBody] string permission)
    {
        await _realmService.ChangePlayerPermissionAsync(realmId, player, permission);

        return NoContent();
    }
}

src/RealmHelper.Web/Pages/Realm/Bedrock/Backups.cshtml.cs
using Microsoft.AspNetCore.Mvc;

using RealmHelper.Application.Services;
using RealmHelper.Domain.Models.Minecraft;
using RealmHelper.Web.Models;
using RealmHelper.Web.Utils;

namespace RealmHelper.Web.Pages.Realm.Bedrock;

public class Backups : OwnedBedrockRealmModel
{
    [FromQuery(Name = "Page")] 
    public int BackupsPage { get; set; } = 1;

    public Backup[] BackupArray { get; set; } = default!;
    
    public Page? CurrentPage { get; set; }

    public Backups(IBedrockRealmService realmService) : base(realmService)
    {
    }

    public override async Task<IActionResult> OnGet(long realmId, CancellationToken cancellationToken)
    {
        await base.OnGet(realmId, cancellationToken);

        var backups = await RealmService.GetBackupsAsync(realmId, cancellationToken);

        if (backups.Length == 0)
            return Page();

        var (start, end, pageSize) = PaginationHelper.GetIndexes(BackupsPage, backups.Length);

        BackupArray = new Backup[pageSize];
        for (var i = start; i < end; i++)
            BackupArray[i] = backups[i];

        CurrentPage = new Page
        {
            Number = PaginationHelper.GetCurrentPage(end),
            Last = PaginationHelper.IsLastPage(end, backups.Length)
        };

        return Page();
    }
}

src/RealmHelper.Web/Pages/Realm/Bedrock/Blacklist.cshtml.cs
using Microsoft.AspNetCore.Mvc;

using RealmHelper.Application.Services;
using RealmHelper.Domain.Models.XboxLive;
using RealmHelper.Web.Models;
using RealmHelper.Web.Utils;

namespace RealmHelper.Web.Pages.Realm.Bedrock;

public class Blacklist : OwnedBedrockRealmModel
{
    private readonly IXboxLiveService _xblService;

    [FromQuery(Name = "Page")]
    public int MembersPage { get; set; } = 1;
    
    public Profile[] Players { get; set; } = default!;

    public Page? CurrentPage { get; set; }

    public Blacklist(IXboxLiveService xblService, IBedrockRealmService realmService) : base(realmService) =>
        _xblService = xblService;

    public override async Task<IActionResult> OnGet(long realmId, CancellationToken cancellationToken)
    {
        await base.OnGet(realmId, cancellationToken);

        var response = await RealmService.GetBlockedPlayersAsync(realmId, cancellationToken);

        if (response.Length == 0)
        {
            Players = Array.Empty<Profile>();

            return Page();
        }

        var (start, end, pageSize) = PaginationHelper.GetIndexes(MembersPage, response.Length);

        var xuids = new string[pageSize];
        for (int i = start, j = 0; i < end; i++, j++)
            xuids[j] = response[i];

        Players = await _xblService.GetProfilesAsync(xuids, cancellationToken);

        CurrentPage = new Page
        {
            Number = PaginationHelper.GetCurrentPage(end),
            Last = PaginationHelper.IsLastPage(end, response.Length)
        };

        return Page();
    }
}

src/RealmHelper.Web/Pages/Realm/Bedrock/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;

using RealmHelper.Application.Services;
using RealmHelper.Domain.Models.XboxLive;

namespace RealmHelper.Web.Pages.Realm.Bedrock;

public class Index : BedrockRealmModel
{
    private readonly IXboxLiveService _xblService;

    public Club Club { get; set; } = default!;
    
    public Profile Owner { get; set; } = default!;

    public ClubActivity[] Activities { get; set; } = default!;

    public Index(IXboxLiveService xblService, IBedrockRealmService realmService) : base(realmService) =>
        _xblService = xblService;

    public override async Task<IActionResult> OnGet(long realmId, CancellationToken cancellationToken)
    {
        var result = await base.OnGet(realmId, cancellationToken);
        
        (Owner, Club, Activities) = await (
            _xblService.GetProfileByXuidAsync(Realm.OwnerUuid, cancellationToken),
            _xblService.GetClubAsync(Realm.ClubId, cancellationToken),
            _xblService.GetClubActivitiesAsync(Realm.ClubId, Constants.PageSize, cancellationToken)
        );

        return result;
    }
}

src/RealmHelper.Web/Pages/Realm/Bedrock/Invites.cshtml.cs
using Microsoft.AspNetCore.Mvc;

using RealmHelper.Application.Services;
using RealmHelper.Domain.Models.XboxLive;
using RealmHelper.Web.Models;
using RealmHelper.Web.Utils;

namespace RealmHelper.Web.Pages.Realm.Bedrock;

public class Invites : OwnedBedrockRealmModel
{
    private readonly IXboxLiveService _xblService;

    [FromQuery(Name = "Page")]
    public int MembersPage { get; set; } = 1;
    
    public Profile[] Profiles { get; set; } = default!;

    public Page CurrentPage { get; set; } = default!;

    public Invites(IXboxLiveService xblService, IBedrockRealmService realmService) : base(realmService) =>
        _xblService = xblService;

    public override async Task<IActionResult> OnGet(long realmId, CancellationToken cancellationToken)
    {
        var result = await base.OnGet(realmId, cancellationToken);

        var players = Realm.Players!.Length;
        
        var blacklist = await RealmService.GetBlockedPlayersAsync(realmId, cancellationToken);

        var (toSkipInvites, _, _) = PaginationHelper.GetIndexes(MembersPage, players);

        var foundInvites = 0;

        var start = -1;

        for (var i = 0; i < players; i++)
        {
            if (foundInvites == toSkipInvites)
            {
                start = i;

                break;
            }
            
            var player = Realm.Players[i];

            if (!player.Accepted && !blacklist.Contains(player.Uuid))
                foundInvites++;
        }

        var end = Math.Min(players, start + Constants.PageSize);

        var pageSize = end - start;

        var xuids = new List<string>(pageSize);
        for (int i = start, j = 0; i < players; i++)
        {
            var player = Realm.Players[i];
            if (!player.Accepted && !blacklist.Contains(player.Uuid))
            {
                if (j < pageSize)
                {
                    xuids.Add(player.Uuid);
                    j++;
                }
                
                foundInvites++;
            }
        }

        Profiles = xuids.Count == 0 
            ? Array.Empty<Profile>() 
            : await _xblService.GetProfilesAsync(xuids.ToArray(), cancellationToken);

        CurrentPage = new Page
        {
            Number = PaginationHelper.GetCurrentPage(end),
            Last = PaginationHelper.IsLastPage(toSkipInvites + Constants.PageSize, foundInvites)
        };

        return result;
    }
}

src/RealmHelper.Web/Pages/Realm/Bedrock/Settings.cshtml.cs
using Microsoft.AspNetCore.Mvc;

using RealmHelper.Application.Services;
using RealmHelper.Domain.Models.Minecraft;
using RealmHelper.Domain.Models.Minecraft.Bedrock;

namespace RealmHelper.Web.Pages.Realm.Bedrock;

public class Settings : OwnedBedrockRealmModel
{
    public Slot<BedrockSlotOptions> ActiveSlot { get; set; } = default!;

    public string InviteCode { get; set; } = default!;
    
    public Settings(IBedrockRealmService realmService) : base(realmService)
    {
    }

    public override async Task<IActionResult> OnGet(long realmId, CancellationToken cancellationToken)
    {
        var result = await base.OnGet(realmId, cancellationToken);

        ActiveSlot = Realm.Slots!.First(s => s.SlotId == Realm.ActiveSlot);
        InviteCode = await RealmService.GetInviteCodeAsync(realmId, cancellationToken);

        return result;
    }
}

src/RealmHelper.Web/Pages/Realm/Java/Index.cshtml.cs
using RealmHelper.Application.Services;

namespace RealmHelper.Web.Pages.Realm.Java;

public class Index : JavaRealmModel
{
    public Index(IJavaRealmService realmService) : base(realmService)
    {
    }
}

src/RealmHelper.Web/ViewComponents/PaginationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RealmHelper.Web.Models;

namespace RealmHelper.Web.ViewComponents;

public class PaginationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(Page page) =>
        View(page);
}

src/RealmHelper.Web/Pages/Realm/Java/Backups.cshtml
@page "/realm/java/{realmId:long}/backups"

@using Humanizer

@model Backups

@{
    ViewData["Title"] = "Backups";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/realm/backups.css" asp-append-version="true" />
}

<div class="realm-backups">
    @if (Model.BackupArray.Length == 0)
    {
        <div>
            <h1 class="title empty">No backups</h1>
            
            <form>
                <input type="file" name="world" id="world-input" accept=".mcworld" />
                <button type="button" class="light-button">UPLOAD CUSTOM WORLD</button>
            </form>
        </div>
    }
    else
    {
        <div>
            <h2 class="title">Backups</h2>
            
            <div>
                <form>
                    <input type="file" name="world" id="world-input" accept=".mcworld" />
                    <button type="button" class="light-button">UPLOAD CUSTOM WORLD</button>
                </form>

                <ul class="box backups">
                    @foreach (var backup in Model.BackupArray)
                    {
                        <li class="backup" data-backup-id="@backup.Id">
                            <div class="backup-header">
                                <span class="world-name">@backup.Metadata.Name</span>

                                <div class="backup-manage">
                                    <img class="img-button" data-download src="~/img/actions/download.png" alt="" />
                                    <img class="img-button" data-upload src="~/img/actions/upload.png" alt=""/>
                                </div>
                            </div>

                            <div class="metadata">
                                <ul>
                                    <li>
                                        Version: @backup.Metadata.Version
                                    </li>
                                    <li>
                                        Gamemode: @backup.Metadata.GameMode.ToString()
                                    </li>
                                    <li>
                                        Difficulty: @backup.Metadata.Difficulty.ToString()
                                    </li>
                                </ul>

                                <span>@DateTimeOffset.Parse(backup.Id).Humanize()</span>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>

        @await Component.InvokeAsync("Pagination", Model.CurrentPage)
    }
</div>

@section Scripts
{
    <script>
        const worldInput = document.getElementById("world-input");
        const button = worldInput.nextElementSibling;
    
        button.addEventListener("click", () => button.classList.contains("off") ? undefined : worldInput.click());
        
        worldInput.addEventListener("change", async () => {
            await makeRequest(
                "@Html.Raw(Url.Action("UploadBackup", "JavaRealm", new { realmId = Model.Realm.Id, slotId = Model.Realm.ActiveSlot }))",
                "Uploading the world...",
                "The world has been uploaded",
                "post",
                new FormData(worldInput.form),
                true,
                button
            );
            
            worldInput.value = null;
        });
    
        for (const img of document.querySelectorAll("[data-download]"))
            img.addEventListener("click", () =>
                {
                    const backupId = img.closest(".backup").getAttribute("data-backup-id");
                    
                    const a = document.createElement("a");
                    a.href = "@Url.Action("DownloadBackup", "JavaRealm", new { realmId = Model.Realm.Id, slotId = Model.Realm.ActiveSlot, backupId = "{0}" })".replace("{0}", backupId);
                    
                    document.body.appendChild(a);
                    
                    a.click();
                    
                    document.body.removeChild(a);
                }
            );
        
        const images = document.querySelectorAll("[data-upload]");
        
        for (const img of images)
            img.addEventListener("click", async () => 
                {
                    const backupId = img.closest(".backup").getAttribute("data-backup-id");
                    
                    await makeRequest(
                        "@Url.Action("UploadBackup", "JavaRealm", new { realmId = Model.Realm.Id, slotId = Model.Realm.ActiveSlot, backupId = "-1" })".replace("-1", backupId),
                        "Uploading the backup...",
                        "The backup has been uploaded",
                        "post",
                        undefined,
                        false,
                        img,
                        images
                    );
                });
    </script>
}

src/RealmHelper.Web/Pages/Realm/Java/Index.cshtml
@page "{realmId:long}"

@model Index

@using Humanizer

@using RealmHelper.Application.Utils

@using Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Overview";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/realm/overview.css" asp-append-version="true" />
}

<div class="realm-overview">
    <div class="box">
        <div class="realm-header" style="--background: url(../../img/overview-bg.png)">
            <img src="https://mc-heads.net/avatar/@Model.Realm.Owner" alt="" class="realm-icon">
    
            <div class="realm-info">
                <span class="realm-name">@Model.Realm.Name</span>
                <span class="realm-motd">@Model.Realm.Motd</span>
            </div>
        </div>
    
        <ul class="realm-body">
            <li class="realm-entry">
                <span class="key">State</span>
                <span class="value">@Model.Realm.State.Transform(To.LowerCase, To.TitleCase)</span>
            </li>
    
            <li class="realm-entry">
                <span class="key">Status</span>
                <span class="value">@(Model.Realm.Expired ? "Expired" : "Running")</span>
            </li>
    
            @if (!Model.Realm.Expired && Model.Realm.IsOwner(User))
            {
                <li class="realm-entry">
                    <span class="key">Expires in</span>
                    <span class="value">@("day".ToQuantity(Model.Realm.DaysLeft))</span>
                </li>
            }
    
            <li class="realm-entry">
                <span class="key">Owner</span>
                <span class="value">@Model.Realm.Owner</span>
            </li>
        </ul>
    </div>
</div>

src/RealmHelper.Web/Pages/Realm/Java/Invites.cshtml
@page "/realm/java/{realmId:long}/invites"

@model Invites

@{
    ViewData["Title"] = "Invites";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/realm/invites.css" asp-append-version="true" />
}

<div class="realm-invites">
    @if (Model.Players.Length == 0)
    {
        <h1 class="title empty">No invites</h1>

        return;
    }
    
    <div>
        <h2 class="title">Invites</h2>
        
        <ul class="invites">
            @foreach (var player in Model.Players)
            {
                <li class="box invite">
                    <img class="info-icon" src="https://mc-heads.net/avatar/@player.Uuid" alt="" />

                    <a href="/realm/java/@Model.Realm.Id/member/@player.Uuid" class="info-name">
                        @player.Name
                    </a>
                </li>
            }
        </ul>
    </div>

    @await Component.InvokeAsync("Pagination", Model.CurrentPage)
</div>

src/RealmHelper.Web/Pages/Realm/Java/Member.cshtml
@page "/realm/java/{realmId:long}/member/{memberId}"

@model Member

@{
    ViewData["Title"] = Model.Player.Name;
}

@section Styles
{
    <link rel="stylesheet" href="~/css/realm/member.css" asp-append-version="true" />
}

<div class="realm-member">
    <div class="box">
        @if (Model.IsRealmOwned && !Model.IsOwner)
        {
            if (Model.IsInvited)
            {
                <img data-tippy-content="Delete invite" class="img-button main-action" src="~/img/actions/uninvite.png" alt="" />
            }
            else if (!Model.IsInRealm)
            {
                <img data-tippy-content="Invite" class="img-button main-action" src="~/img/actions/invite.png" alt="" />
            }
            else
            {
                <img data-tippy-content="Kick" class="img-button main-action" src="~/img/actions/delete.png" alt="" />
            }
        }

        <img class="member-icon" src="https://mc-heads.net/avatar/@Model.Player.Uuid" alt=""/>

        <ul class="member-info">
            <li>
                <span class="info-name">Username</span>

                <span class="info-value">@Model.Player.Name</span>
            </li>
            
            <li>
                <span class="info-name">Status</span>

                @if (Model.IsInvited)
                {
                    <span class="info-value">Invited</span>
                }
                else if (Model.IsInRealm || Model.IsOwner)
                {
                    <span class="info-value">@(Model.IsOnline ? "Online" : "Offline")</span>
                }
                else
                {
                    <span class="info-value">Not in the Realm</span>
                }
            </li>
            
            @if (Model.IsInRealm && Model.IsRealmOwned && !Model.IsOwner)
            {
                <li>
                    <span class="info-name">Permission</span>

                    <select class="info-value" name="permission">
                        <option value="deop"></option>
                        <option value="op" @(Model.Player.Operator ? "selected" : "")></option>
                    </select>
                </li>
            }
        </ul>
    </div>
</div>

@if (Model.IsRealmOwned && !Model.IsOwner)
{
    @section Scripts
    {
        <script>
            tippy(".main-action", { arrow: false });
        
            document.querySelector(".main-action").addEventListener("click", async function() {
                @if (Model.IsInvited)
                {
                    @:const url = "@Url.Action("Uninvite", "JavaRealm", new { realmId = Model.Realm.Id, player = Model.Player.Uuid })";
                    @:const processToast = "Deleting the invite...";
                    @:const successToast = "The invite has been deleted";
                    @:const method = "delete";
                }
                else if (!Model.IsInRealm)
                {
                    @:const url = "@Url.Action("Invite", "JavaRealm", new { realmId = Model.Realm.Id, player = Model.Player.Uuid })";
                    @:const processToast = "Inviting the player...";
                    @:const successToast = "The player has been invited";
                    @:const method = "post";
                }
                else
                {
                    @:const url = "@Url.Action("Uninvite", "JavaRealm", new { realmId = Model.Realm.Id, player = Model.Player.Uuid })";
                    @:const processToast = "Kicking the player...";
                    @:const successToast = "The player has been kicked";
                    @:const method = "delete";
                }
                
                await makeRequest(url, processToast, successToast, method, undefined, true, this);
            });
            
            new TomSelect(document.querySelector("select[name=permission]"), {
                onInitialize: function () {
                    this.control_input.disabled = true;
                },
                render: {
                    item: (data) => `<img class="img-button" alt=\"\" src=\"/img/permissions/${data.value.toLowerCase() === "op" ? "operator" : "member"}.png\" />`,
                    option: (data) => `<img class="img-button" alt=\"\" src=\"/img/permissions/${data.value.toLowerCase() === "op" ? "operator" : "member"}.png\" />`
                },
                onChange: async function (permission) {
                    await makeRequest(
                        "@Url.Action("Op", "JavaRealm", new { realmId = Model.Realm.Id, player = Model.Player.Uuid })",
                        "Saving the permission...",
                        "The permission has been saved",
                        permission === "op" ? "post" : "delete"
                    );
                }
            });
        </script>
    }
}